export const metadata = {
  title: 'NotesApp',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    return (
    <div>
        <main className="flex-1">
            {children}
        </main>
    </div>
  )
}