import UnAuthNavbar from "@/components/Navbar/unAuthNavbar";

export const metadata = {
  title: 'NotesApp',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    return (
    <div className="min-h-screen flex flex-col">
        <div className="sticky top-0 z-50 bg-white/40 backdrop-blur shadow-sm">
            <UnAuthNavbar />
        </div>
        <main className="flex-1 overflow-y-auto">
            {children}
        </main>
    </div>
  )
}