import { getServerSession } from "next-auth"
import { authOptions } from "../api/auth/[...nextauth]/options"
import { redirect } from "next/navigation";
import AuthNavbar from "@/components/Navbar/authnavbar";

export const metadata = {
  title: 'NotesApp',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    const session = await getServerSession(authOptions);

    if(!session){
        redirect('/');
    }

    return (
    <div className="min-h-screen flex flex-col">
        <div className="sticky top-0 z-50">
            <AuthNavbar />
        </div>
        <main className="flex-1 overflow-y-auto">
            {children}
        </main>
    </div>
  )
}